### ISSUE TITLE
cukes fail

### ISSUE THREAD

**Issue by tansaku** [enkanba/foodok#3]
cukes fail with a series of these issues:

```
undefined method `presigned_post' for nil:NilClass
Did you mean?  presence_in (NoMethodError)
./app/controllers/dishes_controller.rb:205:in `set_s3_direct_post'
features/backend/dishes/add_new_dish.feature:31:in `When I fill in "Название" with "Плов"'
features/backend/dishes/add_new_dish.feature:20:in `When I fill in "Название" with "<Title>"'

```

each of which open a new tab with output - ideally show and open page should be turned off for batch running

**Comment by enkanba** [comment]
Removed after hook for cucumber that generated these pages. After all I can manually add a step with save_and_open when in trouble.
